import React, { useEffect } from 'react';
import { motion } from 'framer-motion';

const Security = () => {
    useEffect(() => {
        window.scrollTo(0, 0);
    }, []);

    return (
        <div className="min-h-screen bg-[var(--bg-main)] py-32 px-4 flex justify-center">
            <motion.div 
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                className="max-w-4xl w-full bg-[var(--bg-card)] p-12 md:p-16 rounded-[3rem] shadow-2xl border border-[var(--border-color)] prose dark:prose-invert prose-slate prose-lg"
            >
                <h1 className="text-4xl md:text-5xl font-black mb-8 text-[var(--text-main)] font-cairo">Security Overview</h1>
                <p className="text-[var(--text-muted)] font-medium leading-relaxed mb-6">Enterprise-grade security for your academic records.</p>
                <p>Protecting student data and ensuring the absolute authenticity of academic certificates is our highest priority at Aqooni Digital. This page outlines the practices we employ to keep your data safe and secure.</p>
                
                <h2 className="text-2xl font-bold mt-8 mb-4">1. Data Encryption</h2>
                <p>All data transmitted between your browser and our servers is encrypted using industry-standard TLS protocols. At rest, sensitive academic and administrative data is encrypted in our databases using AES-256 encryption.</p>

                <h2 className="text-2xl font-bold mt-8 mb-4">2. Certificate Authenticity</h2>
                <p>Certificates generated by our system are equipped with unique cryptographic hashes and QR codes. This ensures that any digital or physical copy can be instantly verified against our immutable database, preventing forgery.</p>

                <h2 className="text-2xl font-bold mt-8 mb-4">3. Access Control</h2>
                <p>We employ strict Role-Based Access Control (RBAC). Teachers can only access attendance tools and their specific classes, while Administrators hold broader privileges. Super Admins monitor the overall health of the platform.</p>

                <h2 className="text-2xl font-bold mt-8 mb-4">4. Infrastructure & Backups</h2>
                <p>Our platform is hosted on secure, compliant cloud infrastructure. We perform automated daily backups with geo-redundancy to ensure your school's data is never lost due to localized hardware failures.</p>

                <h2 className="text-2xl font-bold mt-8 mb-4">5. Vulnerability Management</h2>
                <p>We run continuous automated security scans and perform periodic manual assessments of our codebase and infrastructure to identify and patch potential vulnerabilities before they can be exploited.</p>
            </motion.div>
        </div>
    );
};

export default Security;
